AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 
  AWS SAM Template for a Python Lambda function integrated with DynamoDB.
Resources:
  # Define Python Lambda Function
  MyPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aitc-lamba-function
      Handler: lamba-function.lambda_handler
      Runtime: python3.13
      CodeUri: ./src
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: visitor-count-table
      Environment:
        Variables:
          TABLE_NAME: visitor-count-table


  # Define DynamoDB Table
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor-count-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

      
# Output for Lambda Function
Outputs:
  MyLambdaFunctionArn:
    Description: "ARN of the deployed Lambda function"
    Value: !GetAtt MyPythonFunction.Arn

  # Output for DynamoDB Table
  DynamoDBTableName:
    Description: "Name of the DynamoDB Table"
    Value: !Ref visitor-count-table
