name: Deploy Backend 

on:
  push:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/backend/**'  # Run on changes to /backend
  pull_request:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/backend/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Run Super Linter 
      - name: Run Linter
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false  # Ensure pipeline fails if lint error

      # Build backend 
      - name: Build Backend
        run: |
          cd AWS-Cloud-Resume-Challenge/backend
          npm ci
          npm run build

      # Create artifact for deploy
      - name: Upload Site Files
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: |
            .AWS-Cloud-Resume-Challenge/backend/build 


deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    # Check out repository 
    - name: Checkout Code
      uses: actions/checkout@v4.2

    # Setup AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    # Package SAM template
    - name: Package SAM Template
      run: |
        sam package \
          --template-file AWS-Cloud-Resume-Challenge/backend/IaC//backend-iac.yml \
          --s3-bucket aitc-s3\
          --output-template-file AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml

    # Deploy SAM template
    - name: Deploy SAM Template
      run: |
        sam deploy \
          --template-file backend-iac.yml \
          --stack-name aitc-backend-stack \
          --capabilities CAPABILITY_IAM \
          --region us-east-1

  smoke-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Run Cypress Tests
      - name: Run Smoke Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          config-file: cypress.json
