name: Deploy Backend 
on:
  push:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/backend/**'  # Run on changes to /backend
  pull_request:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/backend/**' 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Validate SAM Template
      - name: Validate SAM Template
        run: |
          sam validate --template-file AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml

      # Build SAM App
      - name: Build SAM Application
        run: |
          cd AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml
          sam build

      # Create Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-build-artifact
          path: AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml/.aws-sam/build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: sam-build-artifact

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          cd backend
          pytest tests/unit

      # Run Integration Tests
      - name: Run Integration Tests
        run: |
          cd backend
          pytest tests/integration

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: sam-build-artifact

      # Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Package SAM Template
      - name: Package SAM Template
        run: |
          sam package \
            --template-file AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml \
            --s3-bucket aitc-s3 \
            --output-template-file AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml

      # Step 5: Upload Packaged Template Artifact
      - name: Upload Packaged Template Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-packaged-template
          path: |
            AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml

      # Step 6: Deploy SAM Template
      - name: Deploy SAM Template
        run: |
          sam deploy \
            --template-file AWS-Cloud-Resume-Challenge/backend/IaC/backend-iac.yml \
            --stack-name aitc-backend-stack \
            --capabilities CAPABILITY_IAM \
            --region us-east-1

      # Step 7: Test Deployment
      - name: Test Deployment
        run: |
          aws cloudformation describe-stacks --stack-name aitc-backend-stack
