# ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Other build steps

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures this runs after the build stage
    steps:
      - name: Run Tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures this runs after the test stage
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

# Running the az deployment group create command here applies your infrastructure changes only if the build and test stages succeed.
#  deploy entire infrastructure with a single command:
      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group <resource-group-name> \
            --template-file mainTemplate.json \
            --parameters location=<your-location> \
                        resourcePrefix=<your-prefix>
