name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/frontend/**'  # Run on changes to files in /frontend
  pull_request:
    branches:
      - main
    paths:
      - 'AWS-Cloud-Resume-Challenge/frontend/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Run Super Linter 
      - name: Run Linter
        uses: github/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false  # Ensure pipeline fails if lint error

      # Build application
      - name: Build Frontend
        run: |
          cd AWS-Cloud-Resume-Challenge/frontend
          npm ci
          npm run build

      # Create artifact for deploy
      - name: Upload Site Files
        uses: actions/upload-artifact@v4
        with:
          name: site-files
          path: |
            .AWS-Cloud-Resume-Challenge/frontend/build 
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Check out repository 
      - name: Checkout Code
        uses: actions/checkout@v4.2

      # Download build artifact from build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: site-files
          path: ./site-files

      # Login to AWS
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy frontend to S3
      - name: Deploy Frontend
        run: |
          aws s3 sync ./site-files s3://aitc-s3

  smoke-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Run Cypress Tests
      - name: Run Smoke Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
          config-file: cypress.json
